print(" ")
print(" ")
print(" ")
print(" ")
print("Hello Human being!")
username = input("What is your name? ")
print(" ")
print(" ")
print("Hi "+username+"!")
ask1 = input("Do you want to hear a joke? (Yes/No) ")
print(" ")
print(" ")
if ask1 == "Yes" : 
	print("What do you call a fake noodle? ")
	print(" ")
	print(" ")
	print(" ")
	print("An Impasta!")
else:
	ask2 = input("Fine.... Are you sure? (Yes/No) ")
	if ask2 == "No" : 
		print("What do you call a fake noodle? ")
		print(" ")
		print(" ")
		print(" ")
		print("An Impasta!")

	else: 
		print("Okay, I'm just trying to have a little fun  ; )")
print(" ")
print(" ")
weather = input("What is the weather like today? ")
print(" ")
print(" ")
print("Hmm... "+weather+"?? Same here, buckaroo!!!")
print(" ")
print(" ")
print("Well, "+username+", my Mom is callling so I have to say goodbye for now. Nice Chat! xoxoxoxoxx")
